name: GluchyLifesteal
version: '${project.version}'
main: deaf.GluchyLifesteal.GluchyLifesteal
api-version: 1.20
authors: [ deaf ]
commands:
  alifesteal:
    description: Main command for the Lifesteal plugin
    usage: /<command> [check|get|give|remove|reload] [args]
    permission: alifesteal.admin
  wyplacserce:
    description: Withdraw a heart as an item
    usage: /wyplacserce
    permission: alifesteal.use
permissions:
  alifesteal.admin:
    description: Allows access to admin commands
    default: op
  alifesteal.use:
    description: Allows access to user commands
    default: true
